#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Build script for Clinical Trial Data Downloader.

Usage:
    python build.py           # Build with PyInstaller (onedir)
    python build.py --clean   # Clean build artifacts first
    python build.py --onefile # Build single exe instead of directory
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
DIST = ROOT / "dist"
BUILD = ROOT / "build"


def check_pyinstaller():
    try:
        import PyInstaller  # noqa: F401
        return True
    except ImportError:
        print("PyInstaller not installed. Run: pip install pyinstaller")
        return False


def clean():
    print("Cleaning build artifacts...")
    for d in [BUILD, DIST]:
        if d.exists():
            try:
                shutil.rmtree(d)
            except PermissionError:
                print(f"  Warning: cannot remove {d} (files locked). Skip.")
    for f in ROOT.glob("*.spec"):
        f.unlink()
    version_file = ROOT / "version_info.txt"
    if version_file.exists():
        version_file.unlink()
    print("Done.")


def create_version_info():
    """Create Windows version info file for the exe."""
    from core.constants import APP_VERSION, APP_NAME_EN
    major, minor, patch = APP_VERSION.split(".")
    content = f"""VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [StringTable(
        u'080404B0',
        [StringStruct(u'CompanyName', u'Damon Liang'),
         StringStruct(u'FileDescription', u'{APP_NAME_EN}'),
         StringStruct(u'FileVersion', u'{APP_VERSION}.0'),
         StringStruct(u'InternalName', u'ClinicalTrialDownloader'),
         StringStruct(u'LegalCopyright', u'Copyright (C) 2026 Damon Liang'),
         StringStruct(u'OriginalFilename', u'ClinicalTrialDownloader.exe'),
         StringStruct(u'ProductName', u'{APP_NAME_EN}'),
         StringStruct(u'ProductVersion', u'{APP_VERSION}.0')])
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [2052, 1200])])
  ]
)
"""
    version_file = ROOT / "version_info.txt"
    version_file.write_text(content, encoding="utf-8")
    print(f"Created: {version_file}")
    return str(version_file)


def create_spec(onefile=False):
    """Generate PyInstaller spec file."""
    from core.constants import APP_VERSION

    icon_path = ROOT / "assets" / "icon.ico"
    icon_str = str(icon_path).replace("\\", "/") if icon_path.exists() else ""
    version_str = str(ROOT / "version_info.txt").replace("\\", "/") if (ROOT / "version_info.txt").exists() else ""

    # Use forward slashes to avoid escape sequence issues
    main_py = str(ROOT / "main.py").replace("\\", "/")
    templates_dir = str(ROOT / "ctrdata" / "templates").replace("\\", "/")
    assets_dir = str(ROOT / "assets").replace("\\", "/")
    changelog_file = str(ROOT / "CHANGELOG.md").replace("\\", "/")

    spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py — do not edit manually.

a = Analysis(
    ['{main_py}'],
    pathex=[],
    binaries=[],
    datas=[
        ('{templates_dir}', 'ctrdata/templates'),
        ('{assets_dir}', 'assets'),
        ('{changelog_file}', '.'),
    ],
    hiddenimports=[
        'PySide6.QtWidgets', 'PySide6.QtCore', 'PySide6.QtGui',
        'PySide6.QtWebEngineCore',
        'pandas', 'qtawesome', 'pyqtdarktheme', 'darkdetect',
        'jinja2',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'scipy', 'tkinter.test',
        'unittest', 'pytest', 'jupyter', 'IPython',
        'PyQt6', 'PyQt5', 'PyQt6.QtCore', 'PyQt6.QtGui', 'PyQt6.QtWidgets',
        'numba', 'llvmlite', 'pyarrow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

"""
    if onefile:
        spec += f"""exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ClinicalTrialDownloader',
    debug=False,
    strip=False,
    upx=True,
    console=False,
    icon='{icon_str}',
    version='{version_str}',
)
"""
    else:
        spec += f"""exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ClinicalTrialDownloader',
    debug=False,
    strip=False,
    upx=True,
    console=False,
    icon='{icon_str}',
    version='{version_str}',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    name='ClinicalTrialDownloader',
)
"""
    spec_path = ROOT / "build.spec"
    spec_path.write_text(spec, encoding="utf-8")
    print(f"Created: {spec_path}")
    return str(spec_path)


def build(onefile=False):
    if not check_pyinstaller():
        sys.exit(1)

    print(f"\nBuilding {'single exe' if onefile else 'directory'} package...\n")

    create_version_info()
    spec_path = create_spec(onefile=onefile)

    cmd = ["pyinstaller", "--clean", "--noconfirm", spec_path]
    print(f"Running: {' '.join(cmd)}\n")

    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode == 0:
        output_dir = DIST / "ClinicalTrialDownloader"
        print(f"\nBuild successful!")
        print(f"Output: {output_dir}")
        if (output_dir / "ClinicalTrialDownloader.exe").exists():
            print(f"Executable: {output_dir / 'ClinicalTrialDownloader.exe'}")
    else:
        print(f"\nBuild failed with exit code {result.returncode}")
        sys.exit(result.returncode)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Build Clinical Trial Data Downloader")
    parser.add_argument("--clean", action="store_true", help="Clean build artifacts")
    parser.add_argument("--onefile", action="store_true", help="Build single exe (slower startup)")
    args = parser.parse_args()

    if args.clean:
        clean()

    build(onefile=args.onefile)


if __name__ == "__main__":
    main()
