# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py — do not edit manually.

a = Analysis(
    ['D:/Liangjianlin/project/Personal AI Project/Clinicaltrial docs downloader/v0.3 new/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('D:/Liangjianlin/project/Personal AI Project/Clinicaltrial docs downloader/v0.3 new/ctrdata/templates', 'ctrdata/templates'),
        ('D:/Liangjianlin/project/Personal AI Project/Clinicaltrial docs downloader/v0.3 new/assets', 'assets'),
        ('D:/Liangjianlin/project/Personal AI Project/Clinicaltrial docs downloader/v0.3 new/CHANGELOG.md', '.'),
    ],
    hiddenimports=[
        'PySide6.QtWidgets', 'PySide6.QtCore', 'PySide6.QtGui',
        'pandas', 'qtawesome', 'pyqtdarktheme', 'darkdetect',
        'jinja2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'scipy', 'tkinter.test',
        'unittest', 'pytest', 'jupyter', 'IPython',
        'PyQt6', 'PyQt5', 'PyQt6.QtCore', 'PyQt6.QtGui', 'PyQt6.QtWidgets',
        'numba', 'llvmlite', 'pyarrow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ClinicalTrialDownloader',
    debug=False,
    strip=False,
    upx=True,
    console=False,
    icon='D:/Liangjianlin/project/Personal AI Project/Clinicaltrial docs downloader/v0.3 new/assets/icon.ico',
    version='D:/Liangjianlin/project/Personal AI Project/Clinicaltrial docs downloader/v0.3 new/version_info.txt',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    name='ClinicalTrialDownloader',
)
